media:
  input: src/assets/images
  output: /src/assets/images
content:
  - name: nosotros
    label: Nosotros
    path: src/data/aboutUs.json
    type: file
    fields:
      - name: text
        label: Texto
        type: text
        required: true
        options:
          autoresize: true
      - name: image
        label: Imagen
        type: image
        required: true
        options:
            input: src/assets/images/contacto
            output: /src/assets/images/contacto
            path: src/assets/images/contacto 
      - name: mission
        label: Misión
        type: text
        required: true
        options:
          autoresize: true
      - name: vision
        label: Visión
        type: text
        required: true
        options:
          autoresize: true
  - name: blogs
    label: Blogs
    path: src/data/blogs.json
    type: file
    list: true
    fields: 
      - name: title
        label: Titulo
        type: string
        required: true
      - name: date
        label: Fecha
        type: date
        required: true
      - name: image
        label: Imagen
        type: image
        required: true
        options:
          input: src/assets/images/blogs
          output: /src/assets/images/blogs
          path: src/assets/images/blogs
      - name: text
        label: Texto
        type: text
        required: true
        options:
          autoresize: true
  - name: clientes
    label: Clientes
    path: src/data/clientsLogos.json
    type: file
    list: true
    fields:
      - name: name
        label: Nombre
        type: string
        required: true
      - name: logo
        label: Logo
        type: image
        required: true
        options:
          input: src/assets/images/clientes
          output: /src/assets/images/clientes
          path: src/assets/images/clientes
  - name: contacto
    label: Contacto
    path: src/data/contactPage.json
    type: file
    fields:
      - name: description
        label: Texto
        type: text
        required: true
        options:
          autoresize: true
      - name: image
        label: Imagen
        type: image
        required: true
        options:
          input: src/assets/images/contacto
          output: /src/assets/images/contacto
          path: src/assets/images/contacto
  - name: preguntas_frecuentes
    label: Preguntas frecuentes
    path: src/data/faqInfo.json
    type: file
    list: true
    fields:
      - name: question
        label: Pregunta
        type: text
        required: true
        options:
          autoresize: true
      - name: answer
        label: Respuesta
        type: text
        required: true
        options:
          autoresize: true
  - name: hero_slides
    label: Carrusel hero
    path: src/data/heroSlides.json
    type: file
    list: true
    fields:
      - name: title
        label: Título
        type: string
        required: true
      - name: description
        label: Descripción
        type: text
        required: true
        options:
          autoresize: true
      - name: ctaText
        label: Texto botón
        type: string
        required: true
      - name: bgImage
        label: Imagen de fondo
        type: image
        required: true
        options:
          input: src/assets/images/hero
          output: /src/assets/images/hero
          path: src/assets/images/hero
  - name: galeria
    label: Galería
    path: src/data/projects.json
    type: file
    list: true
    fields:
      - name: image
        label: Imagen
        type: image
        required: true
        options:
          input: src/assets/images/galeria
          output: /src/assets/images/galeria
          path: src/assets/images/galeria
      - name: tag
        label: Etiqueta
        type: string
        required: true
  - name: servicios
    label: Servicios
    path: src/data/services.json
    type: file
    list: true
    fields: 
      - name: title
        label: Nombre
        type: string
        required: true
      - name: description
        label: Descripción
        type: text
        required: true
        options:
          autoresize: true
      - name: image
        label: Imagen
        type: image
        required: true
        options:
          input: src/assets/images/servicios
          output: /src/assets/images/servicios
          path: src/assets/images/servicios
  - name: soluciones
    label: Soluciones (landing page)
    path: src/data/solutionsLanding.json
    type: file
    list: true
    fields:
      - name: name
        label: Nombre
        type: string
        required: true
      - name: image
        label: Imagen
        type: image
        required: true
        options:
          input: src/assets/images/soluciones
          output: /src/assets/images/soluciones
          path: src/assets/images/soluciones
        
        
        
        
        
        
    
        
        
        